MACHINES =
{
  "hclaudeS" =>  "192.168.56.110",
}


Vagrant.configure("2") do |config|
  # same for both nodes
  config.vm.box = "koalephant/debian12"
  #config.vm.box = "debian/bookworm64"

  config.vm.synced_folder File.expand_path("shared", __dir__), "/vagrant"

  MACHINES.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        vb.name = name
      end
      node.vm.provision "shell", inline: "sudo apt update && sudo apt upgrade -y && sudo apt install -y curl"
      node.vm.provision "shell", path: "script/install_k3s.sh"
    end
  end
end