MACHINES =
{
  "hclaudeS" =>  "192.168.56.110",
  "hclaudeSW" => "192.168.56.111"
}


Vagrant.configure("2") do |config|
  # same for both nodes
  config.vm.box = "koalephant/debian12"
  #config.vm.box = "debian/bookworm64"

  MACHINES.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
        vb.name = name
      end
      node.vm.provision "shell", inline: "sudo apt update && sudo apt upgrade -y && sudo apt install -y curl"
      node.vm.provision "shell", path: "scripts/install_k3s.sh", args: [name]
    end
  end
end