
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "hclaudeS"

  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provider "hclaude" do |vb|
	vb.memory = "512"
	vb.cpus = 1
	vb.name = "hclaude"
  end

end