MACHINES =
{
  "hclaude-vm" =>  "192.168.56.110",
}


Vagrant.configure("2") do |config|
  # same for both nodes
  config.vm.box = "koalephant/debian12"
  #config.vm.box = "debian/bookworm64"

  #config.vm.synced_folder File.expand_path("shared", __dir__), "/vagrant"

  MACHINES.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 4
        vb.name = name
      end
      node.vm.network "forwarded_port", guest: 8080, host: 8080
      node.vm.provision "shell", path: "scripts/install.sh", env: { "ARGOCD_PORT" => "8080" }
    end
  end
end